name: Rust

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
          fail-fast: false
          matrix:
            include:
              - target: x86_64-pc-windows-gnu
                archive: zip
              - target: x86_64-unknown-linux-musl
                archive: tar.gz tar.xz tar.zst
    steps:    
    - uses: actions/checkout@v3
    - name: Compile
      id: compile
      uses: rust-build/rust-build.action@v1.4.4
      with:
        RUSTTARGET: x86_64-unknown-linux-musl
        UPLOAD_MODE: none
    #   run: cargo build --verbose --release
    # - name: Run tests
    #   run: cargo test --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: |
          ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.compile.outputs.BUILT_CHECKSUM }}
